language: cpp
sudo: required

matrix:
  include:
   # - os: linux
   #   compiler: gcc
   #   addons: &gcc5
   #     apt:
   #       sources: ['ubuntu-toolchain-r-test']
   #       packages: ['g++-5']
   #   env: COMPILER='g++-5' BUILD_TYPE='Release'
    - os: osx
      osx_image: xcode9.3
      compiler: clang
      env: COMPILER='clang++' BUILD_TYPE='Release'

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew tap Electrux/ccp4m && brew install yaml-cpp ccp4m          ; fi
# - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update && sudo apt-get install libyaml-cpp-dev libboost-all-dev ; fi
  - printf 'travis\ntravis@travis.org' | ccp4m
script:
  - ccp4m project build
  - ls ./src
  - ccp4m project test
  - bin/ls_extended
after_script:
  - ccp4m project clean
  - ccp4m clean
